// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220609052728_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.DataModel.City", b =>
                {
                    b.Property<int>("ctId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stId")
                        .HasColumnType("int");

                    b.HasKey("ctId");

                    b.HasIndex("stId");

                    b.ToTable("cities");
                });

            modelBuilder.Entity("DAL.DataModel.Country", b =>
                {
                    b.Property<int>("cntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Countryname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cntId");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("DAL.DataModel.State", b =>
                {
                    b.Property<int>("stId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cntId")
                        .HasColumnType("int");

                    b.HasKey("stId");

                    b.HasIndex("cntId");

                    b.ToTable("states");
                });

            modelBuilder.Entity("DAL.DataModel.City", b =>
                {
                    b.HasOne("DAL.DataModel.State", "State")
                        .WithMany()
                        .HasForeignKey("stId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.DataModel.State", b =>
                {
                    b.HasOne("DAL.DataModel.Country", "Country")
                        .WithMany()
                        .HasForeignKey("cntId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
